algo = input("Digite algo: ")
print("O tipo primitivo desse valor é ", type(algo))
print("Só twm espaços? ", algo.isspace())
print("É um número? ",algo.isnumeric())
print("É alfabético? ",algo.isalpha())
print("É alfanumerico?",algo.isalnum())
print("Esta em maiúsculas?",algo.isupper())
print("Esta em minusculas?",algo.islower())
print("Esta capitalozada?",algo.isascii())

