nome = str(input("Digite seu nome: ")).strip()
print("Analisando seu nome...")
print(f"Seu nome em maiusculas é {nome.upper()}")
print(f"Seu nome em maiusculas é {nome.lower()}")
print(f"Seu nome tem ao todo {len(nome) - nome.count(" ")} letras")
#print(f"O primeiro nome tem {nome.find(" ")} letras")
separa = nome.split()
print(f"Seu primeiro nome é {separa[0]} e ele tem tem {len(separa[0])} letras")
